[package]
name = "speedtest_mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
env_logger = "0.11.5"
log = "0.4.22"
speedtest-rs = "0.2.0"
tokio = { version = "1.41.0", features = ["full"] }
